server.port=8080
spring.datasource.url=jdbc:postgresql://ep-frosty-shape-aovy7l6d.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IPCDrW5HqUv2
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Properties (Prod mode: hide SQL to save memory and logs)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=S0Y4Z0pSdWpXbk1xNHQ3dyF6JUMqRi1KYU5kUmdVa1hwMnM1dT h4L0E/RChHK0tiUGVTaFZtWXEzdDZ3OXo=